name: Deploy to EC2

on:
  push:
    branches:
      - main  # main 브랜치에 push가 발생할 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.SEAN_FROM_TONY_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.SEAN_FROM_TONY_AWS_ACCESS_KEY_SECRET }}
        aws-region: ap-northeast-2
    
    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli

    - name: Invoke AWS Lambda function
      run: |
        aws lambda invoke \
          --function-name healthkungya-AI-Priavte-CD \
          response.json
    
    - name: Display Lambda response
      run: cat response.json
